name: endemik_db
description: Aplikasi database burung endemik
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  dio: ^5.4.3+1
  photo_view: ^0.15.0 # Untuk zoom gambar
  cached_network_image: ^3.3.1 # Opsional: Untuk caching gambar dari network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true